---
- name: beadando_F5P678
  hosts: serverB
  become: yes
  vars: 
    csomag_neve: "http"
  roles:
   # - raid0_lvm
   # - raid0
    - mdadm
    - mount
    - journal_persist_log
    - packet-install
   
  tasks:
    - name: ping
      ansible.builtin.ping:


